module.exports = {
  // MIGRATION: "migrations",
  USER: "users",
  SUPERADMIN: "superAdmin",
  WIDGETPACKAGES: "widgetPackages",
  ADMIN: "admin",
  CALLDETAILS: "callDetails",
  CUSTOMER: "customer",
  TICKETS: "tickets",
  MIGRATION: "migration",
  

  // ROLE_MASTER: "roles_master",
  // USER_ROLE: "user_roles",
  // USER_DEVICE: "user_devices",
  // SENDER_DETAILS: "sender_details",
  // MONEY_TRANSFER: "money_transfers",
  // ORDER: "orders",
  // RECEIVER_DETAILS: "receiver_details",
  // PAYMENT_DETAILS: "payment_details",
  // PAYMENT_MODES_MASTER: "payment_modes_master",
  // ACCOUNT_TYPES_MASTER: "account_types_master",
  // COUNTRY: "countries_master",
  // SOURCE_OF_FUND: "source_of_funds_master",
  // OCCUPATION_STATUS: "occupation_statuses_master",
  // PURPOSE: "purposes_master",
  // CURRENCY: "currencies_master",
  // OTP: "otps",
  // ORDER_LOG: "order_logs",
  // CURRENCY_EXCHANGE: "currency_exchanges",
  // SETTLEMENT_RATE: "settlement_rates",
  // CUSTOMER_DETAILS: "customer_details",
  // RATE_CARD: "rate_cards_master",
  // TRAVEL_CARD: "travel_cards",
  // CARD_ISSUER_MASTER: "card_issuers_master",
  // FUNDING_OPTION_MASTER: "funding_options_master",
  // RATE_ALERT: "rate_alerts",
  // BONUS_POINT: "bonus_points",
  // PARTNER_GROUPS: "channel_partner_groups",
  // PARTNER_ALLOCATIONS: "channel_partner_allocations",
  // RECEIVER_COUNTRY_MASTER: "receiver_countries_master",
  // NOTIFICATION: "notifications",
};
